export const Routes = {
  root: "/",
  signIn: "/auth/sign-in",
  signUp: "/auth/sign-up",
  forgotPassword: "/auth/forgot-password",
  profile: "/profile",
  messages: "/messages",
  giftCard: "/gift-card",
  success: "/success",
  cancel: "/cancel",
  bookings: "/bookings",
  policy: "/policy",
  terms: "/terms",
  sequence: {
    hireLabour: "/hire-labour",
    bookDelivery: "/book-delivery",
    bookMove: "/book-move",
  },
  bookMoveQuotes: "/book-move/quotes",
  bookMoveQuoteDetails: "/book-move/quote-details",
  hireLabourQuotes: "/hire-labour/quotes",
  hireLabourQuoteDetails: "/hire-labour/quote-details",
};
